import AppKit
import Foundation

/// Pasteboard type identifiers that ClipKeeper reads and writes.
enum PBType {
    static let string = NSPasteboard.PasteboardType.string.rawValue            // public.utf8-plain-text
    static let rtf = NSPasteboard.PasteboardType.rtf.rawValue                  // public.rtf
    static let rtfd = NSPasteboard.PasteboardType.rtfd.rawValue                // com.apple.flat-rtfd
    static let html = NSPasteboard.PasteboardType.html.rawValue                // public.html
    static let url = NSPasteboard.PasteboardType.URL.rawValue                  // public.url
    static let urlName = "public.url-name"
    static let fileURL = NSPasteboard.PasteboardType.fileURL.rawValue          // public.file-url
    static let legacyFilenames = "NSFilenamesPboardType"
    static let png = NSPasteboard.PasteboardType.png.rawValue                  // public.png
    static let tiff = NSPasteboard.PasteboardType.tiff.rawValue                // public.tiff
    static let jpeg = "public.jpeg"
    static let heic = "public.heic"
    static let gif = "com.compuserve.gif"
    static let color = NSPasteboard.PasteboardType.color.rawValue              // com.apple.cocoa.pasteboard.color
    static let webArchive = "com.apple.webarchive"

    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    static let source = "org.nspasteboard.source"

    static let imageTypes: [String] = [png, tiff, jpeg, heic, gif]
    static let richTypes: [String] = [rtfd, rtf, html]
}

/// A full copy of the pasteboard: every item with every type. This is what
/// gets written back on paste, so a paste is identical to the original copy.
struct PasteboardSnapshot: Equatable {
    /// Each element is one pasteboard item: type identifier → data.
    var items: [[String: Data]]

    init(items: [[String: Data]]) {
        self.items = items
    }

    /// Captures the current pasteboard contents. Large TIFF duplicates of a
    /// PNG are dropped; they are regenerated on paste.
    static func capture(from pasteboard: NSPasteboard = .general) -> PasteboardSnapshot {
        var items: [[String: Data]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var dict: [String: Data] = [:]
            let types = item.types.map(\.rawValue)
            let hasPNG = types.contains(PBType.png)
            let hasUTF8 = types.contains(PBType.string)
            for type in types {
                if type == PBType.tiff && hasPNG { continue }
                if PasteboardSnapshot.isTranslatedType(type, hasUTF8: hasUTF8) { continue }
                let started = Date()
                if let data = item.data(forType: NSPasteboard.PasteboardType(type)) {
                    dict[type] = data
                }
                let ms = Date().timeIntervalSince(started) * 1000
                if ms > 50 { NSLog("slow pasteboard read: %@ took %.0f ms", type, ms) }
            }
            if !dict.isEmpty { items.append(dict) }
        }
        return PasteboardSnapshot(items: items)
    }

    /// Types the pasteboard server derives from other types on demand. Reading
    /// one can block until the owning app services the request, so they are
    /// skipped. The originals carry the same content.
    static func isTranslatedType(_ type: String, hasUTF8: Bool) -> Bool {
        if hasUTF8, type == "public.utf16-external-plain-text" || type == "public.utf16-plain-text" { return true }
        if type.hasPrefix("CorePasteboardFlavorType") { return true }
        if type.hasPrefix("dyn.") { return true }
        let legacy = ["NSStringPboardType", "NSFilenamesPboardType", "NSURLPboardType", "NSRTFPboardType", "NSRTFDPboardType", "NSHTMLPboardType", "NSTIFFPboardType", "NSPDFPboardType", "NSColorPboardType"]
        if legacy.contains(type) && type != PBType.legacyFilenames { return true }
        let lower = type.lowercased()
        if lower.hasSuffix(" pasteboard type") || lower.hasSuffix(" pboard type") { return true }
        return false
    }

    /// Human names for the formats present, main content first: "PNG, TIFF" or "RTF, HTML, Plain text".
    var formatSummary: String {
        let order: [(String, String)] = [
            (PBType.png, "PNG"), (PBType.jpeg, "JPEG"), (PBType.tiff, "TIFF"), (PBType.heic, "HEIC"), (PBType.gif, "GIF"),
            (PBType.rtfd, "RTFD"), (PBType.rtf, "RTF"), (PBType.html, "HTML"), (PBType.webArchive, "Web archive"),
            (PBType.fileURL, "File references"), (PBType.url, "URL"), (PBType.color, "Color"),
            (PBType.string, "Plain text"),
        ]
        let present = allTypes
        var names: [String] = []
        for (type, name) in order where present.contains(type) { names.append(name) }
        let known = Set(order.map(\.0)) .union([PBType.legacyFilenames, PBType.source, PBType.urlName])
        let other = present.subtracting(known).filter { !$0.hasPrefix("dyn.") && !$0.hasPrefix("org.nspasteboard") }
        if !other.isEmpty { names.append(other.count == 1 ? "1 other type" : "\(other.count) other types") }
        return names.joined(separator: ", ")
    }

    /// Builds a snapshot that holds only a plain string.
    static func plainText(_ string: String) -> PasteboardSnapshot {
        PasteboardSnapshot(items: [[PBType.string: Data(string.utf8)]])
    }

    /// Builds a snapshot that holds a PNG image, plus a TIFF made from it.
    static func image(png: Data) -> PasteboardSnapshot {
        PasteboardSnapshot(items: [[PBType.png: png]])
    }

    static func color(_ color: NSColor, text: String) -> PasteboardSnapshot {
        var dict: [String: Data] = [PBType.string: Data(text.utf8)]
        if let data = try? NSKeyedArchiver.archivedData(withRootObject: color, requiringSecureCoding: true) {
            dict[PBType.color] = data
        }
        return PasteboardSnapshot(items: [dict])
    }

    /// All types of the first item, in pasteboard order.
    var types: [String] { items.first.map { Array($0.keys) } ?? [] }

    var allTypes: Set<String> { Set(items.flatMap { $0.keys }) }

    func has(_ type: String) -> Bool { allTypes.contains(type) }

    func data(for type: String) -> Data? {
        for item in items { if let d = item[type] { return d } }
        return nil
    }

    var string: String? {
        guard let d = data(for: PBType.string) else { return nil }
        return String(data: d, encoding: .utf8) ?? String(data: d, encoding: .utf16)
    }

    var totalByteCount: Int { items.reduce(0) { $0 + $1.values.reduce(0) { $0 + $1.count } } }

    /// Writes every item and type back to the pasteboard.
    /// Returns the new change count so the monitor can ignore this write.
    @discardableResult
    func write(to pasteboard: NSPasteboard = .general, markSource bundleID: String? = nil) -> Int {
        pasteboard.clearContents()
        var pbItems: [NSPasteboardItem] = []
        for (index, item) in items.enumerated() {
            let pbItem = NSPasteboardItem()
            for (type, data) in item {
                pbItem.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            if let png = item[PBType.png], item[PBType.tiff] == nil, let tiff = NSImage(data: png)?.tiffRepresentation {
                pbItem.setData(tiff, forType: .tiff)
            }
            if index == 0, let bundleID {
                pbItem.setString(bundleID, forType: NSPasteboard.PasteboardType(PBType.source))
            }
            pbItems.append(pbItem)
        }
        pasteboard.writeObjects(pbItems)
        return pasteboard.changeCount
    }

    // MARK: Serialization (binary property list)

    func serialized() throws -> Data {
        let array: [[String: Data]] = items
        return try PropertyListSerialization.data(fromPropertyList: array, format: .binary, options: 0)
    }

    init?(serialized: Data) {
        guard let obj = try? PropertyListSerialization.propertyList(from: serialized, options: [], format: nil),
              let array = obj as? [[String: Data]] else { return nil }
        self.items = array
    }
}
